"""auto-gen-uuid in semantic mem table

Revision ID: 4a0e6b4e6ced
Revises: c2e0daa22197
Create Date: 2025-11-22 05:41:03.483619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0e6b4e6ced'
down_revision: Union[str, Sequence[str], None] = 'c2e0daa22197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('semantic_memories', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('idx_semantic_memories_embedding'), table_name='semantic_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_semantic_memories_id'), table_name='semantic_memories')
    op.create_index(op.f('ix_semantic_memories_id'), 'semantic_memories', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_memories_id'), table_name='semantic_memories')
    op.create_index(op.f('ix_semantic_memories_id'), 'semantic_memories', ['id'], unique=False)
    op.create_index(op.f('idx_semantic_memories_embedding'), 'semantic_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('semantic_memories', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
